### ISSUE TITLE
Adding channel to replicator break the app

### ISSUE THREAD

**Issue by richard457** [Rudiksz/couchbase_lite_dart#10]
`replicator.channels = ['15']`;
with message like 
```
/lib/arm64/libCouchbaseLiteC.so (bool c4Internal::tryCatch<bool>(C4Error*, fleece::function_ref<c4Internal::tryCatch<bool> ()>)+20) (BuildId: decfb458ac869f8d60250e4cbc6578629a8834be)
      #04 pc 000000000019b0cc  /data/app/rw.flipper-4LOGONSlQXbZXgZw0FyKuQ==/lib/arm64/libCouchbaseLiteC.so
```

**Comment by richard457** [comment]
The platform is android and on version 0.4.0

**Comment by richard457** [comment]
Steps to reproduce:

1. Connect on a database with no replicator channel added
2. Then add a channel later and connect to the same database again
3. It breaks, then remove channel and connect again it still break.

**Comment by richard457** [comment]
Another Test:

1. Uninstall the app and remove the channel
2. Connect the database with no channel then it works.
3. Conclusion the `replicator.channels = ['15'];` break the app once it is added.

**Comment by Rudiksz** [comment]
I can't reproduce the error either way. You need to set the channels when you create the replicator by passing them in the constructor.

`replicator.channels = ['15'];` has no effect whatsoever

**Comment by richard457** [comment]
@Rudiksz I tested more than a couple of weeks ago, and this is the stack trace

```
I/LiteCore [DB](14123): {DB#4}==> N8litecore14SQLiteDataFileE /data/user/0/rw.flipper/app_flutter/main.cblite2/db.sqlite3 @0xf2ecac90
I/LiteCore [DB](14123): {DB#4} Opening database
I/LiteCore [DB](14123): {DB#5}==> N8litecore14SQLiteDataFileE /data/user/0/rw.flipper/app_flutter/main.cblite2/db.sqlite3 @0xf2ec6af0
I/LiteCore [DB](14123): {DB#5} Opening database
I/LiteCore [Actor](14123): Starting Scheduler<0xf31ed970> with 4 threads
I/LiteCore [Sync](14123): {Repl#6}==> N8litecore4repl10ReplicatorE /data/user/0/rw.flipper/app_flutter/main.cblite2/ -
I/LiteCore [Sync](14123): {Repl#6} Push=continuous, Pull=continuous, Options={{auth:{password:"********", type:"Basic", username:"admin"}, channels:["15"]}}
I/LiteCore [Sync](14123): {C4Replicator#7}==> N10c4Internal18C4RemoteReplicatorE 0xf2b12558 @0xf2b12558
I/LiteCore [Sync](14123): {C4Replicator#7} Starting Replicator {Repl#6}
I/LiteCore [Query](14123): {Query#8}==> N8litecore11SQLiteQueryE SELECT * WHERE table=$VALUE @0xaee0a498
I/LiteCore [Query](14123): {Query#8} Compiling N1QL query: SELECT * WHERE table=$VALUE
I/LiteCore [Sync](14123): {Repl#6} Scanning for pre-existing conflicts...
I/LiteCore [Sync](14123): {Repl#6} Found 0 conflicted docs in 0.015 sec
I/LiteCore [Query](14123): {Query#8} Compiled as SELECT fl_result(fl_root(_doc.body)) FROM kv_default AS _doc WHERE (fl_value(_doc.body, 'table') = $_VALUE) AND (_doc.flags & 1 = 0)
I/LiteCore [Sync](14123): {Repl#6} No local checkpoint 'cp-Sj8AexKjTnyh5hI91CAj/B3CfNk='
I/LiteCore [Query](14123): {QueryEnum#9}==> N8litecore21SQLiteQueryEnumeratorE 0xf2b7a54c @0xf2b7a54c
I/LiteCore [Query](14123): {QueryEnum#9} Created on {Query#8} with 1 rows (1018 bytes) in 0.908ms
I/LiteCore [Query](14123): {QueryEnum#9} Deleted
F/libc    (14123): Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xadb9c788 in tid 14385 (1.ui), pid 14123 (rw.flipper)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:11/RSR1.201013.001/6903271:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-12-23 07:47:57+0200
pid: 14123, tid: 14385, name: 1.ui  >>> rw.flipper <<<
uid: 10156
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xadb9c788
    eax f2b7a510  ebx adb9d924  ecx adb86398  edx af2ca7e0
    edi af2ca7e0  esi f31f3c80
    ebp c221807c  esp c2217f8c  eip adb9c788
backtrace:
      #00 pc 005bc788  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #01 pc 001646b1  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (c4Internal::C4QueryEnumeratorImpl::next()+49) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #02 pc 005bd923  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #03 pc 00164656  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (bool fleece::function_ref<bool ()>::callback_fn<c4queryenum_next::$_4>(int)+38) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #04 pc 005bd923  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #05 pc 0015c231  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (bool c4Internal::tryCatch<bool>(C4Error*, fleece::function_ref<bool ()>)+33) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #06 pc 005bd923  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #07 pc 00162e64  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (c4queryenum_next+84) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #08 pc 005bd923  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #09 pc 001105ea  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (CBLResultSet::next()+138) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #10 pc 005bd923  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so!libCouchbaseLiteC.so (offset 0x5a5000) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #11 pc 0011054b  /data/app/~~ieFs_Y2mcEyoYu1QlN3kXA==/rw.flipper-8G9qoLV3wisGf4K8uUfFdw==/lib/x86/libCouchbaseLiteC.so (CBLResultSet_Next+27) (BuildId: ad23b8410a86cb0e714b250e6f81aa9619f37c42)
      #12 pc 000335b1  <anonymous:b2f00000>
```

**Comment by richard457** [comment]
From the error, it seems like the error is in Query or somewhere, not the channels, created a simple application with query observer on it there was no problem, and I run the same Query on now the real project that has any queries then the error comes.
the Query example  ```
final q = Query(ProxyService.database.db,
                                          'SELECT * WHERE table=\$VALUE AND id=\$ID');

                                      q.parameters = {
                                        'VALUE': AppTables.user,
                                        'ID': loginResponse.id.toString()
                                      };
                                      final log = Logging.getLogger('OTP:');
                                      final user = q.execute(); //or a listner Query
```

**Comment by richard457** [comment]
And this is on **V.0.4.0** but the works in **V.0.3.0**

**Comment by Rudiksz** [comment]
The new ResultSet object changes the way results are handled. I suspect you get a segfault because you are mixing the old and new approach somehow. Probably calling `allResults` and/or `next`, `rowArray`, `rowDict` in the wrong contexts. There is indeed a a bug when flagging the ResultSet as invalid after calling `allResults`, which causes a segfault. The solution is to either use allResults or iterate the results using `next/rowArray/rowDict`, but not both.

---
The nuts and bolts if you are interested:

You need to loop through the results with the Fleece API (basically using `next`, `rowArray` and `rowDict` methods to get the row as a Fleece value) and you parse the row into your application whichever you preferer.
Basically 

```
  while (results.next()) {
    final rowAsArray = results.rowArray;
    // or
    final rowAsDict = results.rowDict;

    // Do whatever you need with the results: usually parse them into a Dart object using the Fleece API
    print(rowAsArray[0].asString);
  }
  results.dispose();
```

This is supposedly faster because it accesses the underlying C memory without having to parse it into a Dart List first. However there are a few caveats:
1) The C API only allows to traverse the result set forwards, so once you reached the end, there is no way to repeat the operation.

2) Once you looped through the result set, there's nothing else you can do to it because, but to dispose it. And you should dispose of it, to eliminate memory leaks. It is kept in memory until you are done parsing it.

3) retrieving the current row is only valid until the next `next` call. Basically the body of your while loop. If you were to store the `rowAsArray` variable in a someplace else (an external object) and try to access it later you'd get undefined behaviour (most likely segfaults). There's no easy way to prevent that on the library level because Dart's ffi is super complicated and incomplete when it comes to finalizers and memory ownership.  The Couchbase api has methods to "retain" those values, ~~which I will probably expose later on~~ I already exposed, but then you have to do manual memory management. Think disposing TextEditingControlles, AnimationControllers in Flutter. You would have to do the same with your data entities. Bleh. Since I have plain old Dart data classes anyway, I parse the row into them and call it a day. It's like json deserialization: you parse a string into a Dart object which then you then parse into your Data classes and throw away the string and the intermediary Dart map, except here you throw away the C memory when you're done parsing it into your Data classes and now all memory management is done automatically for you by the Dart VM.

4) I kept the 'allResults' getter for backwards compatibility and to be in line with the other SDK's, but what it really does is what I described in point 3. It just parses the results set and returns a pure Dart list (decoding the json representation of the FLDict, basically what jsonDecode does to a String). And disposes the results set for you. The consequence is that once you call allResults on a ResultSet object, you can simply throw it away, because none of the other methods will work. I would strongly discourage using it.

**Comment by richard457** [comment]
Tested thes piece of code
 ```
 final q = Query(_databaseService.db, 'SELECT * WHERE table=\$VALUE');

    q.parameters = {'VALUE': 'users'};

    q.addChangeListener((results) {
      while (results.next()) {
        final rowAsArray = results.rowArray;
        // final rowAsDict = results.rowDict;
        log.d(rowAsArray);
        // log.d(rowAsDict);
        // print(rowAsArray[0]);
      }
      results.dispose();

      // for (Map map in results.allResults) {
      //   map.forEach((key, value) {
      //     if (!_users.contains(User.fromMap(value))) {
      //       log.d(User.fromMap(value));
      //       _users.add(User.fromMap(value));
      //     }
      //   });
      //   notifyListeners();
      // }
    });
```
 **final rowAsArray = results.rowArray;** always return nothing but  **final rowAsDict = results.rowDict;** works, but again the 
result returned is hard to access here is result returned from rowDict  
`{"*":{"email":"murag@gmail.com","id":"094c4a79-ebf2-4719-afa0-b01e8c9e0a00","name":"+777788899","active":false,"channels":["47"],"createdAt":null,"table":"users","userId":"47"}}`

**Comment by richard457** [comment]
**{"*":{**  is added which makes it hard to access the object.

**Comment by richard457** [comment]
A workaround I used to have is to loop through and take only value
  ```
map.forEach((key, value) {
          if (!_users.contains(User.fromMap(value))) {
            log.d(User.fromMap(value));
            _users.add(User.fromMap(value));
          }
        });
```

**Comment by Rudiksz** [comment]
> final rowAsArray = results.rowArray; always return nothing but final rowAsDict = results.rowDict; works, but again the
> result returned is hard to access here is result returned from rowDict
> {"*":{"email":"murag@gmail.com","id":"094c4a79-ebf2-4719-afa0-b01e8c9e0a00","name":"+777788899","active":false,"channels":["47"],"createdAt":null,"table":"users","userId":"47"}}

The value returned by rowArray and rowDict are FLArray and FLDict, so you should use their api to access the data. Printing them out just calls the `json` method on them (FLArray apparently has a bug in the toString method). Just use FLArray.json instead.

The `*` in the resultset is standard couchbase lite behaviour, common to all SDK's. It depends how you write your queries and is added only when you do "select *" queries.

For example this query:

> `SELECT` table as t, id WHERE table=\$VALUE AND id=\$ID 

would return

`{"id":"rudolf","t":"user"}`

A better workaround is to use the FLDict methods to access your value, ie: `rowAsDict['*'].asMap` would give you the actual result set as an FLValue, which you can then again manipulate using the the Fleece api. Since this is couchbase behaviour and it depends on the query you write, there's not much I can do on the library level.

Remember that FLDict and FLArray behave just like Dart arrays and maps in respect to the `[]` operator, or you can use the `()` operaror to access nested values as a json path.

Ie: `rowAsDict['*'].asMap['id'].asString` is the same as `rowAsDict('*.id').asString`

**Comment by richard457** [comment]
Interestingly, the Query with a special character such as  +12025550149
 will never execute!
