### ISSUE TITLE
Can Update Query work?

### ISSUE THREAD

**Issue by richard457** [Rudiksz/couchbase_lite_dart#8]
I am wondering if something like this UPDATE category  SET focused=false  WHERE  id<>'$id'  can work, I played with it but seems to not work, if it can is there any example? thank you so much.

**Comment by Rudiksz** [comment]
The couhcbase lite core library does not suport UPDATE, and as far as I know none of the platform SDK's support it either because they use the same core under the hood.

You can find the supported grammar here
https://github.com/couchbase/couchbase-lite-core/blob/e25884358722da0939f325b8f0a31c53ccbafad2/LiteCore/Query/N1QL_Parser/n1ql.leg

Unless you need to update throusands of documents at once, doing a save for each document shouldn't be a problem. 
Use batch operation to group your writes together (ie wrap them in db.beginBatch() and db.endBatch() calls)

Per the documentation
```
  /// Begins a batch operation, similar to a transaction. You **must** later call
  /// `endBatch` to end (commit) the batch.
  /// -  Multiple writes are much faster when grouped inside a single batch.
  /// -  Changes will not be visible to other database instances on the same database until the batch operation ends.
  /// -  Batch operations can nest. Changes are not committed until the outer batch ends.
  bool beginBatch() {
```
  I haven't tested it yet, but I would expect that query and database listeners should fire only once for each batch.

**Comment by richard457** [comment]
Got it. let me try it out.
